name: Build and Deploy to cPanel

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 📦 Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🛠️ Install NPM Dependencies and Build
        run: |
          rm -rf node_modules
          npm install
          npm run build

      - name: 🚀 Sync Files to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env.example
            README.md
            phpunit.xml
            composer.json
            composer.lock
            package.json
            package-lock.json
            vite.config.js
            tailwind.config.js
